<a href="https://colab.research.google.com/github/ozkar0005/Tecmilenio_Tareas/blob/FUNDAMENTOS_Y_APLICACIONES_DE_IA/Fase3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![svg image](data:image/svg+xml,%3Csvg%20version%3D%221.1%22%20id%3D%22Layer_1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20xmlns%3Axlink%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%22%20x%3D%220px%22%20y%3D%220px%22%0A%09%20viewBox%3D%220%200%201796%20100%22%20style%3D%22enable-background%3Anew%200%200%201796%20100%3B%22%20xml%3Aspace%3D%22preserve%22%3E%0A%3Cstyle%20type%3D%22text%2Fcss%22%3E%0A%09.st0%7Bfill-rule%3Aevenodd%3Bclip-rule%3Aevenodd%3Bfill%3Aurl%28%23SVGID_1_%29%3B%7D%0A%09.st1%7Bclip-path%3Aurl%28%23SVGID_00000121240274182655608510000017605911509184857789_%29%3B%7D%0A%09.st2%7Bfill%3Aurl%28%23SVGID_00000136410921659939037740000014083183155629369760_%29%3B%7D%0A%09.st3%7Bclip-path%3Aurl%28%23SVGID_00000064338599076419636020000012809401988964638116_%29%3B%7D%0A%09.st4%7Bfill%3Aurl%28%23SVGID_00000103971791687048145990000013932511977451091122_%29%3B%7D%0A%09.st5%7Bfill%3Anone%3Bstroke%3A%23FFFFFF%3Bstroke-width%3A2%3Bstroke-miterlimit%3A10%3B%7D%0A%09.st6%7Bfill%3Anone%3Bstroke%3A%23FFFFFF%3Bstroke-width%3A1.5%3Bstroke-miterlimit%3A10%3B%7D%0A%09.st7%7Bfill%3A%23FFFFFF%3B%7D%0A%09.st8%7Bfont-family%3A%27IBMPlexSans%27%3B%7D%0A%09.st9%7Bfont-size%3A32px%3B%7D%0A%09.st10%7Bfill%3A%233D3D3D%3B%7D%0A%09.st11%7Bfill%3A%23939598%3B%7D%0A%09.st12%7Bopacity%3A0.2%3Bfill%3Aurl%28%23SVGID_00000157297371800964624580000000052036904934900156_%29%3Benable-background%3Anew%20%20%20%20%3B%7D%0A%09.st13%7Bfont-family%3A%27IBMPlexSans-Medium%27%3B%7D%0A%3C%2Fstyle%3E%0A%3Crect%20width%3D%221796%22%20height%3D%22100%22%2F%3E%0A%3ClinearGradient%20id%3D%22SVGID_1_%22%20gradientUnits%3D%22userSpaceOnUse%22%20x1%3D%2242.8625%22%20y1%3D%221027.998%22%20x2%3D%2279.71%22%20y2%3D%221027.998%22%20gradientTransform%3D%22matrix%281%200%200%201%200%20-978%29%22%3E%0A%09%3Cstop%20%20offset%3D%220%22%20style%3D%22stop-color%3A%23AB74FF%22%2F%3E%0A%09%3Cstop%20%20offset%3D%220.21%22%20style%3D%22stop-color%3A%23866AFF%22%2F%3E%0A%09%3Cstop%20%20offset%3D%220.75%22%20style%3D%22stop-color%3A%232A4FFF%22%2F%3E%0A%09%3Cstop%20%20offset%3D%221%22%20style%3D%22stop-color%3A%230645FF%22%2F%3E%0A%3C%2FlinearGradient%3E%0A%3Cpath%20class%3D%22st0%22%20d%3D%22M52.4%2C45.9c0-2.3%2C1.8-4.1%2C4.1-4.1s4.1%2C1.8%2C4.1%2C4.1S58.8%2C50%2C56.5%2C50l0%2C0c-2.2%2C0.1-4-1.7-4.1-3.9%0A%09C52.4%2C46%2C52.4%2C46%2C52.4%2C45.9z%20M77.5%2C52.5c-0.8-1.1-1.4-2.3-1.9-3.5c1.2-4.5%2C0.7-8.6-1.8-11.9c-2.9-3.8-8.2-6-14.5-6.1%0A%09c-4.5-0.1-8.8%2C1.7-12%2C4.8c-3%2C3-4.6%2C7.2-4.5%2C11.5c-0.1%2C2.9%2C0.9%2C5.8%2C2.7%2C8.1c0.8%2C0.8%2C1.3%2C1.9%2C1.4%2C3v4.5c-0.8%2C0.5-1.4%2C1.3-1.4%2C2.3%0A%09c0.2%2C1.5%2C1.5%2C2.6%2C3%2C2.4c1.2-0.2%2C2.2-1.1%2C2.4-2.4c0-1-0.5-1.9-1.4-2.3v-4.5c0-2-1-3.3-1.9-4.6c-1.5-1.9-2.2-4.2-2.1-6.5%0A%09c0-3.5%2C1.4-6.9%2C3.8-9.4c2.7-2.7%2C6.3-4.1%2C10-4.1c5.5%2C0%2C9.8%2C1.9%2C12.1%2C5c2%2C2.8%2C2.5%2C6.3%2C1.4%2C9.6c-0.4%2C1.2%2C0.6%2C2.7%2C2.3%2C5.6%0A%09c0.6%2C0.9%2C1.2%2C1.9%2C1.6%2C2.9c-0.9%2C0.7-2%2C1.2-3.1%2C1.5c-0.5%2C0.4-0.7%2C0.9-0.8%2C1.5V65c0%2C0.4-0.1%2C0.8-0.4%2C1.1c-0.3%2C0.2-0.7%2C0.3-1.1%2C0.3%0A%09c-1.6-0.3-3.4-0.7-5.2-1.1v-4.8c0.8-0.5%2C1.4-1.4%2C1.4-2.3c0-1.5-1.2-2.7-2.7-2.7s-2.7%2C1.2-2.7%2C2.7c0%2C1%2C0.5%2C1.9%2C1.4%2C2.3v4.1%0A%09c-0.4-0.1-0.7-0.1-1.1-0.3c-4.5-1.1-4.5-2.6-4.5-3.4v-8.3c3.2-0.7%2C5.4-3.5%2C5.5-6.7c-0.1-3.8-3.3-6.7-7.1-6.6c-3.6%2C0.1-6.4%2C3-6.6%2C6.6%0A%09c0%2C3.2%2C2.3%2C6%2C5.5%2C6.7v8.3c0%2C2%2C0.7%2C4.6%2C6.6%2C6.1c3%2C0.8%2C6%2C1.5%2C9.1%2C1.9c0.3%2C0%2C0.6%2C0.1%2C0.8%2C0.1c1%2C0%2C1.9-0.3%2C2.6-1%0A%09c0.9-0.8%2C1.4-1.9%2C1.4-3.1v-4.5c2-0.8%2C4.1-2%2C4.1-3.7C79.7%2C55.9%2C79%2C54.6%2C77.5%2C52.5z%22%2F%3E%0A%3Cg%3E%0A%09%3Cg%3E%0A%09%09%3Cdefs%3E%0A%09%09%09%3Cpath%20id%3D%22SVGID_00000002383543606002198300000015823331188058885284_%22%20d%3D%22M52.4%2C45.9c0-2.3%2C1.8-4.1%2C4.1-4.1s4.1%2C1.8%2C4.1%2C4.1%0A%09%09%09%09S58.8%2C50%2C56.5%2C50l0%2C0c-2.2%2C0.1-4-1.7-4.1-3.9C52.4%2C46%2C52.4%2C46%2C52.4%2C45.9z%20M77.5%2C52.5c-0.8-1.1-1.4-2.3-1.9-3.5%0A%09%09%09%09c1.2-4.5%2C0.7-8.6-1.8-11.9c-2.9-3.8-8.2-6-14.5-6.1c-4.5-0.1-8.8%2C1.7-12%2C4.8c-3%2C3-4.6%2C7.2-4.5%2C11.5c-0.1%2C2.9%2C0.9%2C5.8%2C2.7%2C8.1%0A%09%09%09%09c0.8%2C0.8%2C1.3%2C1.9%2C1.4%2C3v4.5c-0.8%2C0.5-1.4%2C1.3-1.4%2C2.3c0.2%2C1.5%2C1.5%2C2.6%2C3%2C2.4c1.2-0.2%2C2.2-1.1%2C2.4-2.4c0-1-0.5-1.9-1.4-2.3v-4.5%0A%09%09%09%09c0-2-1-3.3-1.9-4.6c-1.5-1.9-2.2-4.2-2.1-6.5c0-3.5%2C1.4-6.9%2C3.8-9.4c2.7-2.7%2C6.3-4.1%2C10-4.1c5.5%2C0%2C9.8%2C1.9%2C12.1%2C5%0A%09%09%09%09c2%2C2.8%2C2.5%2C6.3%2C1.4%2C9.6c-0.4%2C1.2%2C0.6%2C2.7%2C2.3%2C5.6c0.6%2C0.9%2C1.2%2C1.9%2C1.6%2C2.9c-0.9%2C0.7-2%2C1.2-3.1%2C1.5c-0.5%2C0.4-0.7%2C0.9-0.8%2C1.5V65%0A%09%09%09%09c0%2C0.4-0.1%2C0.8-0.4%2C1.1c-0.3%2C0.2-0.7%2C0.3-1.1%2C0.3c-1.6-0.3-3.4-0.7-5.2-1.1v-4.8c0.8-0.5%2C1.4-1.4%2C1.4-2.3c0-1.5-1.2-2.7-2.7-2.7%0A%09%09%09%09s-2.7%2C1.2-2.7%2C2.7c0%2C1%2C0.5%2C1.9%2C1.4%2C2.3v4.1c-0.4-0.1-0.7-0.1-1.1-0.3c-4.5-1.1-4.5-2.6-4.5-3.4v-8.3c3.2-0.7%2C5.4-3.5%2C5.5-6.7%0A%09%09%09%09c-0.1-3.8-3.3-6.7-7.1-6.6c-3.6%2C0.1-6.4%2C3-6.6%2C6.6c0%2C3.2%2C2.3%2C6%2C5.5%2C6.7v8.3c0%2C2%2C0.7%2C4.6%2C6.6%2C6.1c3%2C0.8%2C6%2C1.5%2C9.1%2C1.9%0A%09%09%09%09c0.3%2C0%2C0.6%2C0.1%2C0.8%2C0.1c1%2C0%2C1.9-0.3%2C2.6-1c0.9-0.8%2C1.4-1.9%2C1.4-3.1v-4.5c2-0.8%2C4.1-2%2C4.1-3.7C79.7%2C55.9%2C79%2C54.6%2C77.5%2C52.5z%22%2F%3E%0A%09%09%3C%2Fdefs%3E%0A%09%09%3CclipPath%20id%3D%22SVGID_00000176740417986926051140000007418691528295814056_%22%3E%0A%09%09%09%3Cuse%20xlink%3Ahref%3D%22%23SVGID_00000002383543606002198300000015823331188058885284_%22%20%20style%3D%22overflow%3Avisible%3B%22%2F%3E%0A%09%09%3C%2FclipPath%3E%0A%09%09%3Cg%20style%3D%22clip-path%3Aurl%28%23SVGID_00000176740417986926051140000007418691528295814056_%29%3B%22%3E%0A%09%09%09%0A%09%09%09%09%3ClinearGradient%20id%3D%22SVGID_00000011735757951680555470000006442623761332390031_%22%20gradientUnits%3D%22userSpaceOnUse%22%20x1%3D%22-1341.4%22%20y1%3D%22805.5%22%20x2%3D%22449.7%22%20y2%3D%22805.5%22%20gradientTransform%3D%22matrix%281%200%200%201%200%20-978%29%22%3E%0A%09%09%09%09%3Cstop%20%20offset%3D%220%22%20style%3D%22stop-color%3A%23AB74FF%22%2F%3E%0A%09%09%09%09%3Cstop%20%20offset%3D%220.21%22%20style%3D%22stop-color%3A%23866AFF%22%2F%3E%0A%09%09%09%09%3Cstop%20%20offset%3D%220.75%22%20style%3D%22stop-color%3A%232A4FFF%22%2F%3E%0A%09%09%09%09%3Cstop%20%20offset%3D%221%22%20style%3D%22stop-color%3A%230645FF%22%2F%3E%0A%09%09%09%3C%2FlinearGradient%3E%0A%09%09%09%0A%09%09%09%09%3Crect%20x%3D%22-1341.4%22%20y%3D%22-876.9%22%20style%3D%22fill%3Aurl%28%23SVGID_00000011735757951680555470000006442623761332390031_%29%3B%22%20width%3D%221791.1%22%20height%3D%221408.8%22%2F%3E%0A%09%09%09%3Cg%3E%0A%09%09%09%09%3Cg%3E%0A%09%09%09%09%09%3Cdefs%3E%0A%09%09%09%09%09%09%0A%09%09%09%09%09%09%09%3Crect%20id%3D%22SVGID_00000072996190263840714970000007889047166468584121_%22%20x%3D%22-1341.4%22%20y%3D%22-876.9%22%20width%3D%221791.1%22%20height%3D%221408.8%22%2F%3E%0A%09%09%09%09%09%3C%2Fdefs%3E%0A%09%09%09%09%09%3CclipPath%20id%3D%22SVGID_00000153694860218795575650000008900673480820130986_%22%3E%0A%09%09%09%09%09%09%3Cuse%20xlink%3Ahref%3D%22%23SVGID_00000072996190263840714970000007889047166468584121_%22%20%20style%3D%22overflow%3Avisible%3B%22%2F%3E%0A%09%09%09%09%09%3C%2FclipPath%3E%0A%09%09%09%09%09%3Cg%20style%3D%22clip-path%3Aurl%28%23SVGID_00000153694860218795575650000008900673480820130986_%29%3B%22%3E%0A%09%09%09%09%09%09%0A%09%09%09%09%09%09%09%3ClinearGradient%20id%3D%22SVGID_00000101098069614077405180000000356714788787315333_%22%20gradientUnits%3D%22userSpaceOnUse%22%20x1%3D%2236%22%20y1%3D%221028.05%22%20x2%3D%2286.5%22%20y2%3D%221028.05%22%20gradientTransform%3D%22matrix%281%200%200%201%200%20-978%29%22%3E%0A%09%09%09%09%09%09%09%3Cstop%20%20offset%3D%220%22%20style%3D%22stop-color%3A%23AB74FF%22%2F%3E%0A%09%09%09%09%09%09%09%3Cstop%20%20offset%3D%220.21%22%20style%3D%22stop-color%3A%23866AFF%22%2F%3E%0A%09%09%09%09%09%09%09%3Cstop%20%20offset%3D%220.75%22%20style%3D%22stop-color%3A%232A4FFF%22%2F%3E%0A%09%09%09%09%09%09%09%3Cstop%20%20offset%3D%221%22%20style%3D%22stop-color%3A%230645FF%22%2F%3E%0A%09%09%09%09%09%09%3C%2FlinearGradient%3E%0A%09%09%09%09%09%09%0A%09%09%09%09%09%09%09%3Crect%20x%3D%2236%22%20y%3D%2224.1%22%20style%3D%22fill%3Aurl%28%23SVGID_00000101098069614077405180000000356714788787315333_%29%3B%22%20width%3D%2250.5%22%20height%3D%2251.9%22%2F%3E%0A%09%09%09%09%09%3C%2Fg%3E%0A%09%09%09%09%3C%2Fg%3E%0A%09%09%09%3C%2Fg%3E%0A%09%09%3C%2Fg%3E%0A%09%3C%2Fg%3E%0A%3C%2Fg%3E%0A%3Ccircle%20class%3D%22st5%22%20cx%3D%2256.5%22%20cy%3D%2245.9%22%20r%3D%225.4%22%2F%3E%0A%3Ccircle%20class%3D%22st6%22%20cx%3D%2248.3%22%20cy%3D%2265%22%20r%3D%221.6%22%2F%3E%0A%3Ccircle%20class%3D%22st6%22%20cx%3D%2264.8%22%20cy%3D%2258.2%22%20r%3D%221.6%22%2F%3E%0A%3Ctext%20transform%3D%22matrix%281%200%200%201%20101.02%2059.33%29%22%20class%3D%22st7%20st8%20st9%22%3EAutoAI%3C%2Ftext%3E%0A%3Crect%20x%3D%22231.1%22%20y%3D%2234%22%20class%3D%22st10%22%20width%3D%221%22%20height%3D%2232%22%2F%3E%0A%3Ctext%20transform%3D%22matrix%281%200%200%201%20256.29%2059.66%29%22%20class%3D%22st11%20st8%20st9%22%3EPart%20of%20IBM%20Watson%C2%AE%20Studio%3C%2Ftext%3E%0A%3ClinearGradient%20id%3D%22SVGID_00000046311962679126569570000008758169430711952785_%22%20gradientUnits%3D%22userSpaceOnUse%22%20x1%3D%22773.8%22%20y1%3D%221028%22%20x2%3D%221796%22%20y2%3D%221028%22%20gradientTransform%3D%22matrix%281%200%200%201%200%20-978%29%22%3E%0A%09%3Cstop%20%20offset%3D%220%22%20style%3D%22stop-color%3A%23161616%22%2F%3E%0A%09%3Cstop%20%20offset%3D%220.52%22%20style%3D%22stop-color%3A%23AB74FF%22%2F%3E%0A%09%3Cstop%20%20offset%3D%220.62%22%20style%3D%22stop-color%3A%23866AFF%22%2F%3E%0A%09%3Cstop%20%20offset%3D%220.88%22%20style%3D%22stop-color%3A%232A4FFF%22%2F%3E%0A%09%3Cstop%20%20offset%3D%221%22%20style%3D%22stop-color%3A%230645FF%22%2F%3E%0A%3C%2FlinearGradient%3E%0A%3Crect%20x%3D%22773.8%22%20style%3D%22opacity%3A0.2%3Bfill%3Aurl%28%23SVGID_00000046311962679126569570000008758169430711952785_%29%3Benable-background%3Anew%20%20%20%20%3B%22%20width%3D%221022.2%22%20height%3D%22100%22%2F%3E%0A%3Ctext%20transform%3D%22matrix%281%200%200%201%201448.1641%2059.46%29%22%20class%3D%22st7%20st13%20st9%22%3EExperiment%20notebook%3C%2Ftext%3E%0A%3C%2Fsvg%3E)
# Experiment Notebook -AutoAI Notebook v3.0.1


This notebook contains the steps and code to demonstrate support of AutoAI experiments in the Watson Machine Learning service. It introduces Python API commands for data retrieval, training experiments, persisting pipelines, testing pipelines, refining pipelines, and scoring the resulting model.

**Note:** Notebook code generated using AutoAI will execute successfully. If code is modified or reordered, there is no guarantee it will successfully execute. For details, see: <a href="https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/autoai-notebook.html">Saving an Auto AI experiment as a notebook</a>

Some familiarity with Python is helpful. This notebook uses Python 3.12 and the `ibm-watsonx-ai` package.


## Notebook goals

The learning goals of this notebook are:
-  Defining an AutoAI experiment
-  Training AutoAI models
-  Comparing trained models
-  Deploying the model as a web service
-  Scoring the model to generate predictions



## Contents

This notebook contains the following parts:

**[Setup](#Setup)**<br>
&nbsp;&nbsp;[Package installation](#Package-installation)<br>
&nbsp;&nbsp;[Watson Machine Learning connection](#Watson-Machine-Learning-connection)<br>
**[Experiment configuration](#Experiment-configuration)**<br>
&nbsp;&nbsp;[Experiment metadata](#Experiment-metadata)<br>
**[Working with completed AutoAI experiment](#Working-with-completed-AutoAI-experiment)**<br>
&nbsp;&nbsp;[Get fitted AutoAI optimizer](#Get-fitted-AutoAI-optimizer)<br>
&nbsp;&nbsp;[Pipelines comparison](#Pipelines-comparison)<br>
&nbsp;&nbsp;[Get pipeline as a scikit-learn pipeline model](#Get-pipeline-as-a-scikit-learn-pipeline-model)<br>
&nbsp;&nbsp;[Inspect pipeline](#Inspect-pipeline)<br>
&nbsp;&nbsp;&nbsp;&nbsp;[Visualize pipeline model](#Visualize-pipeline-model)<br>
**[Deploy and Score](#Deploy-and-Score)**<br>
&nbsp;&nbsp;[Working with spaces](#Working-with-spaces)<br>
**[Running AutoAI experiment with Python API](#Running-the-AutoAI-experiment-with-Python-API)**<br>
**[Next steps](#Next-steps)**<br>
**[Copyrights](#Copyrights)**

<a id="setup"></a>
# Setup

<a id="install"></a>
## Package installation
Before you use the sample code in this notebook, install the following packages:
 - ibm-watsonx-ai,
 - autoai-ts-libs

In [15]:
!pip install ibm-watsonx-ai | tail -n 1
!pip install -U 'autoai-ts-libs>=5.0.2,<5.1' | tail -n 1
!pip install 'scikit-learn>=1.6.1,<1.7' | tail -n 1
!pip install 'jupyter>=1' | tail -n 1

Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<0.29,>=0.27->ibm-watsonx-ai) (4.15.0)
Requirement already satisfied: sortedcontainers~=2.2 in /usr/local/lib/python3.12/dist-packages (from portion->jsonsubschema>=0.0.6->lale<0.10,>=0.9->autoai-ts-libs<5.1,>=5.0.2) (2.4.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<1.7,>=1.6.1) (3.6.0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.12/dist-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter>=1) (2025.3)

<a id="configuration"></a>
# Experiment configuration

<a id="metadata"></a>
## Experiment metadata
This cell defines the metadata for the experiment, including: training_data_references, training_result_reference, experiment_metadata.

In [16]:
from ibm_watsonx_ai.helpers import DataConnection
from ibm_watsonx_ai.helpers import ContainerLocation

training_data_references = [
    DataConnection(
        data_asset_id='94e1fa9e-d460-43f4-9072-55a0a55752e1'
    ),
]
training_result_reference = DataConnection(
    location=ContainerLocation(
        path='auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts',
        model_location='auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/model.zip',
        training_status='auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/training-status.json'
    )
)

In [17]:
experiment_metadata = dict(
    prediction_type='timeseries',
    prediction_columns=['Bitcoin Precio Cierre'],
    csv_separator=',',
    holdout_size=20,
    training_data_references=training_data_references,
    training_result_reference=training_result_reference,
    timestamp_column_name='Fecha',
    backtest_num=4,
    pipeline_type='all',
    customized_pipelines=[],
    lookback_window=-1,
    forecast_window=1,
    max_num_daub_ensembles=3,
    feature_columns=['Bitcoin Precio Cierre', 'Tasa de interes promedio', 'ETF precio cierre'],
    future_exogenous_available=True,
    gap_len=0,
    deployment_url='https://us-south.ml.cloud.ibm.com',
    project_id='3b4a037e-5691-40a1-ba31-4f54c44f1f47',
    numerical_imputation_strategy=['FlattenIterative', 'Linear', 'Cubic', 'Previous']
)

<a id="connection"></a>
## Watson Machine Learning connection

This cell defines the credentials required to work with the Watson Machine Learning service.

**Action**: Provide the IBM Cloud apikey, For details, see [documentation](https://cloud.ibm.com/docs/account?topic=account-userapikey).

In [18]:
import getpass

api_key = getpass.getpass("Please enter your api key (press enter): ")

Please enter your api key (press enter): ··········

In [19]:
from ibm_watsonx_ai import Credentials

credentials = Credentials(
    api_key=api_key,
    url=experiment_metadata['deployment_url']
)

<a id="work"></a>


# Working with completed AutoAI experiment

This cell imports the pipelines generated for the experiment. The best pipeline will be saved as a model.

<a id="get"></a>


## Get fitted AutoAI optimizer

In [20]:
from ibm_watsonx_ai.experiment import AutoAI

pipeline_optimizer = AutoAI(credentials, project_id=experiment_metadata['project_id']).runs.get_optimizer(metadata=experiment_metadata)

Use `get_params()` to retrieve configuration parameters.

In [21]:
pipeline_optimizer.get_params()

{'name': 'Factores',
 'desc': '',
 'prediction_type': 'forecasting',
 'prediction_column': None,
 'prediction_columns': ['Bitcoin Precio Cierre'],
 'timestamp_column_name': 'Fecha',
 'scoring': None,
 'holdout_size': 20,
 'max_num_daub_ensembles': 3,
 't_shirt_size': 'a6c4923b-b8e4-444c-9f43-8a7ec3020110',
 'train_sample_rows_test_size': None,
 'include_only_estimators': None,
 'include_batched_ensemble_estimators': None,
 'backtest_num': 4,
 'lookback_window': -1,
 'forecast_window': 1,
 'backtest_gap_length': 0,
 'cognito_transform_names': None,
 'csv_separator': ',',
 'excel_sheet': None,
 'encoding': 'utf-8',
 'positive_label': None,
 'drop_duplicates': True,
 'outliers_columns': None,
 'text_processing': True,
 'word2vec_feature_number': None,
 'daub_give_priority_to_runtime': None,
 'text_columns_names': None,
 'sampling_type': None,
 'sample_size_limit': None,
 'sample_rows_limit': None,
 'sample_percentage_limit': None,
 'number_of_batch_rows': None,
 'n_parallel_data_connections': None,
 'test_data_csv_separator': ',',
 'test_data_excel_sheet': None,
 'test_data_encoding': 'utf-8',
 'categorical_imputation_strategy': None,
 'numerical_imputation_strategy': None,
 'numerical_imputation_value': None,
 'imputation_threshold': None,
 'retrain_on_holdout': True,
 'feature_columns': ['Bitcoin Precio Cierre',
  'Tasa de interes promedio',
  'ETF precio cierre'],
 'pipeline_types': [<ForecastingPipelineTypes.RandomForestRegressor: 'RandomForestRegressor'>,
  <ForecastingPipelineTypes.ExogenousRandomForestRegressor: 'ExogenousRandomForestRegressor'>,
  <ForecastingPipelineTypes.SVM: 'SVM'>,
  <ForecastingPipelineTypes.ExogenousSVM: 'ExogenousSVM'>,
  <ForecastingPipelineTypes.LocalizedFlattenEnsembler: 'LocalizedFlattenEnsembler'>,
  <ForecastingPipelineTypes.DifferenceFlattenEnsembler: 'DifferenceFlattenEnsembler'>,
  <ForecastingPipelineTypes.FlattenEnsembler: 'FlattenEnsembler'>,
  <ForecastingPipelineTypes.ExogenousLocalizedFlattenEnsembler: 'ExogenousLocalizedFlattenEnsembler'>,
  <ForecastingPipelineTypes.ExogenousDifferenceFlattenEnsembler: 'ExogenousDifferenceFlattenEnsembler'>,
  <ForecastingPipelineTypes.ExogenousFlattenEnsembler: 'ExogenousFlattenEnsembler'>,
  <ForecastingPipelineTypes.MT2RForecaster: 'MT2RForecaster'>,
  <ForecastingPipelineTypes.ExogenousMT2RForecaster: 'ExogenousMT2RForecaster'>,
  <ForecastingPipelineTypes.HoltWinterAdditive: 'HoltWinterAdditive'>,
  <ForecastingPipelineTypes.HoltWinterMultiplicative: 'HoltWinterMultiplicative'>,
  <ForecastingPipelineTypes.Bats: 'Bats'>,
  <ForecastingPipelineTypes.ARIMA: 'ARIMA'>,
  <ForecastingPipelineTypes.ARIMAX: 'ARIMAX'>,
  <ForecastingPipelineTypes.ARIMAX_RSAR: 'ARIMAX_RSAR'>,
  <ForecastingPipelineTypes.ARIMAX_PALR: 'ARIMAX_PALR'>,
  <ForecastingPipelineTypes.ARIMAX_RAR: 'ARIMAX_RAR'>,
  <ForecastingPipelineTypes.ARIMAX_DMLR: 'ARIMAX_DMLR'>],
 'supporting_features_at_forecast': True,
 'numerical_columns': None,
 'categorical_columns': None,
 'confidence_level': None,
 'incremental_learning': None,
 'early_stop_enabled': None,
 'early_stop_window_size': None,
 'time_ordered_data': None,
 'feature_selector_mode': None,
 'run_id': '39aa7057-c366-4fa2-b677-e944f9e1a71c'}

<a id="comparison"></a>
## Pipelines comparison

Use the `summary()` method to list trained pipelines and evaluation metrics information in
the form of a Pandas DataFrame. You can use the DataFrame to compare all discovered pipelines and select the one you like for further testing.

In [22]:
summary = pipeline_optimizer.summary()
best_pipeline_name = list(summary.index)[0]
summary

,Enhancements,Estimator,Winner,validation_symmetric_mean_absolute_percentage_error,holdout_avg_r2,holdout_avg_mean_absolute_error,holdout_avg_root_mean_squared_error,holdout_avg_symmetric_mean_absolute_percentage_error,holdout_mean_absolute_error,holdout_root_mean_squared_error,holdout_symmetric_mean_absolute_percentage_error,holdout_r2,backtest_avg_r2,backtest_avg_mean_absolute_error,backtest_avg_root_mean_squared_error,backtest_avg_symmetric_mean_absolute_percentage_error,backtest_mean_absolute_error,backtest_root_mean_squared_error,backtest_symmetric_mean_absolute_percentage_error,backtest_r2
Pipeline Name,,,,,,,,,,,,,,,,,,,,
Pipeline_9,"HPO, FE",Ensembler,True,1.441087,0.781115,2586.827726,3752.997214,3.348372,2586.827726,3752.997214,3.348372,0.781115,0.556083,1442.973820,1853.554481,1.536793,1442.973820,1853.554481,1.536793,0.556083
Pipeline_15,"HPO, FE",ARIMA,True,1.446792,0.782256,2587.035088,3743.198451,3.341975,2587.035088,3743.198451,3.341975,0.782256,0.554695,1451.133062,1858.034355,1.545583,1451.133062,1858.034355,1.545583,0.554695
Pipeline_13,"HPO, FE",HoltWinters,True,1.448255,0.785097,2604.376078,3718.700412,3.347434,2604.376078,3718.700412,3.347434,0.785097,0.544153,1470.481426,1883.388893,1.566713,1470.481426,1883.388893,1.566713,0.544153

<a id="get_pipeline"></a>
### Get pipeline as a scikit-learn pipeline model

After you compare the pipelines, download and save a scikit-learn pipeline model object from the
AutoAI training job.

**Tip:** To get a specific pipeline, pass the pipeline name in:
```
pipeline_optimizer.get_pipeline(pipeline_name=pipeline_name)
```

In [23]:
!pip install autoai-libs==3.0.1
pipeline_model = pipeline_optimizer.get_pipeline(astype="sklearn")

Requirement already satisfied: autoai-libs==3.0.1 in /usr/local/lib/python3.12/dist-packages (3.0.1)
Requirement already satisfied: numpy<2.1,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from autoai-libs==3.0.1) (2.0.2)
Requirement already satisfied: lale>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from autoai-libs==3.0.1) (0.9.2)
Requirement already satisfied: pandas>=2.2.3 in /usr/local/lib/python3.12/dist-packages (from autoai-libs==3.0.1) (2.2.3)
Requirement already satisfied: parameterized>=0.9 in /usr/local/lib/python3.12/dist-packages (from autoai-libs==3.0.1) (0.9.0)
Requirement already satisfied: scikit-learn<1.7,>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from autoai-libs==3.0.1) (1.6.1)
Requirement already satisfied: xgboost<3.0.0,>=2.1.3 in /usr/local/lib/python3.12/dist-packages (from autoai-libs==3.0.1) (2.1.4)
Requirement already satisfied: black>=22.1.0 in /usr/local/lib/python3.12/dist-packages (from lale>=0.9.0->autoai-libs==3.0.1) (26.3.1)
Requirement already satisfied: hyperopt<=0.2.7,>=0.2 in /usr/local/lib/python3.12/dist-packages (from lale>=0.9.0->autoai-libs==3.0.1) (0.2.7)
Requirement already satisfied: jsonschema<=5 in /usr/local/lib/python3.12/dist-packages (from lale>=0.9.0->autoai-libs==3.0.1) (4.26.0)
Requirement already satisfied: jsonsubschema>=0.0.6 in /usr/local/lib/python3.12/dist-packages (from lale>=0.9.0->autoai-libs==3.0.1) (0.0.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from lale>=0.9.0->autoai-libs==3.0.1) (1.15.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from lale>=0.9.0->autoai-libs==3.0.1) (26.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from lale>=0.9.0->autoai-libs==3.0.1) (4.4.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from lale>=0.9.0->autoai-libs==3.0.1) (4.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.3->autoai-libs==3.0.1) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.3->autoai-libs==3.0.1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.3->autoai-libs==3.0.1) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<1.7,>=1.6.1->autoai-libs==3.0.1) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<1.7,>=1.6.1->autoai-libs==3.0.1) (3.6.0)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost<3.0.0,>=2.1.3->autoai-libs==3.0.1) (2.29.7)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from black>=22.1.0->lale>=0.9.0->autoai-libs==3.0.1) (8.3.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from black>=22.1.0->lale>=0.9.0->autoai-libs==3.0.1) (1.1.0)
Requirement already satisfied: pathspec>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from black>=22.1.0->lale>=0.9.0->autoai-libs==3.0.1) (1.0.4)
Requirement already satisfied: platformdirs>=2 in /usr/local/lib/python3.12/dist-packages (from black>=22.1.0->lale>=0.9.0->autoai-libs==3.0.1) (4.9.4)
Requirement already satisfied: pytokens~=0.4.0 in /usr/local/lib/python3.12/dist-packages (from black>=22.1.0->lale>=0.9.0->autoai-libs==3.0.1) (0.4.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from hyperopt<=0.2.7,>=0.2->lale>=0.9.0->autoai-libs==3.0.1) (1.17.0)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.12/dist-packages (from hyperopt<=0.2.7,>=0.2->lale>=0.9.0->autoai-libs==3.0.1) (3.4.2)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from hyperopt<=0.2.7,>=0.2->lale>=0.9.0->autoai-libs==3.0.1) (1.0.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from hyperopt<=0.2.7,>=0.2->lale>=0.9.0->autoai-libs==3.0.1) (4.67.3)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from hyperopt<=0.2.7,>=0.2->lale>=0.9.0->autoai-libs==3.0.1) (3.1.2)
Requirement already satisfied: py4j in /usr/local/lib/python3.12/dist-packages (from hyperopt<=0.2.7,>=0.2->lale>=0.9.0->autoai-libs==3.0.1) (0.10.9.9)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema<=5->lale>=0.9.0->autoai-libs==3.0.1) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema<=5->lale>=0.9.0->autoai-libs==3.0.1) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema<=5->lale>=0.9.0->autoai-libs==3.0.1) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema<=5->lale>=0.9.0->autoai-libs==3.0.1) (0.30.0)
Requirement already satisfied: portion in /usr/local/lib/python3.12/dist-packages (from jsonsubschema>=0.0.6->lale>=0.9.0->autoai-libs==3.0.1) (2.6.1)
Requirement already satisfied: greenery<=3.3.3 in /usr/local/lib/python3.12/dist-packages (from jsonsubschema>=0.0.6->lale>=0.9.0->autoai-libs==3.0.1) (3.3.3)
Requirement already satisfied: jsonref in /usr/local/lib/python3.12/dist-packages (from jsonsubschema>=0.0.6->lale>=0.9.0->autoai-libs==3.0.1) (1.1.0)
Requirement already satisfied: sortedcontainers~=2.2 in /usr/local/lib/python3.12/dist-packages (from portion->jsonsubschema>=0.0.6->lale>=0.9.0->autoai-libs==3.0.1) (2.4.0)

**Tip:** If you want to check all the details of the model evaluation metrics, use:
```
pipeline_optimizer.get_pipeline_details()
```

<a id="inspect_pipeline"></a>
## Inspect pipeline

<a id="visualize"></a>
### Visualize pipeline model

Preview pipeline model stages as a graph. Each node's name links to a detailed description of the stage.

In [24]:
pipeline_model

TSPipeline(feature_columns=[0],
           steps=[('linear_imputer', linear()),
                  ('<class '
                   "'autoai_ts_libs.srom.estimators.time_series.models.srom_estimators.DifferenceFlattenAutoEnsembler'>",
                   DifferenceFlattenAutoEnsembler(dag_granularity='flat',
                                                  data_transformation_scheme='log',
                                                  estimator=EnsembleRegressor(auto_regression=AutoRegression(best_estimator_so_far=Pipel...
                                                                              total_execution_time=3),
                                                  execution_platform='single_node_complete_search',
                                                  execution_time_per_pipeline=3,
                                                  feature_columns=[0],
                                                  init_time_optimization=True,
                                                  look_ahead_fcolumns=[],
                                                  lookback_win=30,
                                                  n_estimators_for_pred_interval=1,
                                                  n_jobs=1,
                                                  n_leaders_for_ensemble=1,
                                                  pred_win=1,
                                                  store_lookback_history=True,
                                                  target_columns=[0],
                                                  total_execution_time=3))],
           target_columns=[0])

### Calling the `predict` method
If you want to get a prediction by using the pipeline model object, call `pipeline_model.predict()`.

**Note:** If you want to work with a pure sklearn model:
 - add the following parameter to the `get_pipeline` call: `astype='sklearn'`,
 - or `scikit_learn_pipeline = pipeline_model.export_to_sklearn_pipeline()`

<a id="scoring"></a>
## Deploy and Score

In this section you will learn how to deploy and score the model as a web service.

<a id="working_spaces"></a>
### Working with spaces

In this section you will specify a deployment space to organize assets and then deploy and score the model. If you do not have an existing space, you can use the [Deployment Spaces Dashboard](/ml-runtime/spaces?context=wx) to create a new space. Follow these steps:

- Click **New Deployment Space**
- Create an empty space
- Select Cloud Object Storage
- Select Watson Machine Learning instance and press **Create**
- Copy `space_id` and paste it below

**Tip**: You can also use the API to prepare the space for your work. Learn more [here](https://github.com/IBM/watson-machine-learning-samples/blob/master/cloud/notebooks/python_sdk/instance-management/Space%20management.ipynb).

**Action**: Assign or update space ID below.

### Deployment creation

In [25]:
target_space_id = input("Enter your space ID here (press enter): ")

Enter your space ID here (press enter): 06745160-68e0-4dc2-a351-e27770e3b3e1

In [26]:
from ibm_watsonx_ai.deployment import WebService

service = WebService(
    source_instance_credentials=credentials,
    target_instance_credentials=credentials,
    source_project_id=experiment_metadata['project_id'],
    target_space_id=target_space_id
)
service.create(
    model=best_pipeline_name,
    experiment_run_id=pipeline_optimizer.get_params()['run_id'],
    deployment_name='Best_pipeline_webservice'
)

Preparing an AutoAI Deployment...
Published model uid: 39796f3b-f2ed-422b-9483-fcadde3f0aeb
Deploying model 39796f3b-f2ed-422b-9483-fcadde3f0aeb using V4 client.


######################################################################################

Synchronous deployment creation for id: '39796f3b-f2ed-422b-9483-fcadde3f0aeb' started

######################################################################################


initializing
Note: online_url and serving_urls are deprecated and will be removed in a future release. Use inference instead.
....
ready


-----------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_id='9bc1c214-09d0-472a-b984-4ef68627bc9b'
-----------------------------------------------------------------------------------------------

Use the `print` method for the deployment object to show basic information about the service:

In [27]:
print(service)

name: Best_pipeline_webservice, id: 9bc1c214-09d0-472a-b984-4ef68627bc9b, scoring_url: https://us-south.ml.cloud.ibm.com/ml/v4/deployments/9bc1c214-09d0-472a-b984-4ef68627bc9b/predictions, asset_id: 39796f3b-f2ed-422b-9483-fcadde3f0aeb

To show all available information about the deployment, use the `.get_params()` method.

In [28]:
service.get_params()

Note: online_url and serving_urls are deprecated and will be removed in a future release. Use inference instead.

{'entity': {'asset': {'id': '39796f3b-f2ed-422b-9483-fcadde3f0aeb'},
  'chat_enabled': False,
  'custom': {},
  'deployed_asset_type': 'model',
  'hybrid_pipeline_hardware_specs': [{'hardware_spec': {'name': 'S',
     'num_nodes': 1},
    'node_runtime_id': 'auto_ai.ts'}],
  'online': {},
  'status': {'inference': [{'url': 'https://us-south.ml.cloud.ibm.com/ml/v4/deployments/9bc1c214-09d0-472a-b984-4ef68627bc9b/predictions'}],
   'online_url': {'url': 'https://us-south.ml.cloud.ibm.com/ml/v4/deployments/9bc1c214-09d0-472a-b984-4ef68627bc9b/predictions'},
   'serving_urls': ['https://us-south.ml.cloud.ibm.com/ml/v4/deployments/9bc1c214-09d0-472a-b984-4ef68627bc9b/predictions'],
   'state': 'ready'}},
 'metadata': {'created_at': '2026-04-10T17:56:12.337Z',
  'id': '9bc1c214-09d0-472a-b984-4ef68627bc9b',
  'modified_at': '2026-04-10T17:56:12.337Z',
  'name': 'Best_pipeline_webservice',
  'owner': 'IBMid-697001EI08',
  'space_id': '06745160-68e0-4dc2-a351-e27770e3b3e1'},
 'system': {'warnings': [{'id': 'Deprecated',
    'message': 'online_url and serving_urls are deprecated and will be removed in a future release. Use inference instead.'},
   {'id': 'text_generation_deprecation',
    'message': 'The `/text/generation` and `/text/generation_stream` endpoints will be deprecated in an upcoming release and removed in a future release.'}]}}

### Scoring of webservice
You can make a scoring request by calling `score()` on the deployed pipeline.

If you want to work with the web service in an external Python application, follow these steps to retrieve the service object:

 - Initialize the service by `service = WebService(target_instance_credentials=credentials,target_space_id=experiment_metadata['space_id'])`
 - Get deployment_id: `service.list()`
 - Get webservice object: `service.get('deployment_id')`

After that you can call `service.score(score_records_df)` method. The `score()` method accepts `pandas.DataFrame` objects.

<a id="cleanup"></a>
### Deleting deployment
You can delete the existing deployment by calling the `service.delete()` command.
To list the existing web services, use the `service.list()` method.

<a id="run"></a>

## Running the AutoAI experiment with Python API

**Info**: Below cells are `raw` type - in order to run them, change their type to `code` and run them (no need to restart the notebook). You may need to add some additional info.

If you want to run the AutoAI experiment using the Python API, follow these steps. The experiment settings were generated basing on parameters set in the AutoAI UI.

In [29]:
from ibm_watsonx_ai.experiment import AutoAI

experiment = AutoAI(credentials, project_id=experiment_metadata['project_id'])

In [30]:
OPTIMIZER_NAME = 'custom_name'

In [31]:
from ibm_watsonx_ai.helpers import DataConnection
from ibm_watsonx_ai.helpers import ContainerLocation

training_data_references = [
    DataConnection(
        data_asset_id='94e1fa9e-d460-43f4-9072-55a0a55752e1'
    ),
]
training_result_reference = DataConnection(
    location=ContainerLocation(
        path='auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts',
        model_location='auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/model.zip',
        training_status='auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/training-status.json'
    )
)

The new pipeline optimizer will be created and training will be triggered.

In [32]:
pipeline_optimizer = experiment.optimizer(
    name=OPTIMIZER_NAME,
    prediction_type=experiment_metadata['prediction_type'],
    prediction_columns=experiment_metadata['prediction_columns'],
    holdout_size=experiment_metadata['holdout_size'],
    max_number_of_estimators=experiment_metadata['max_num_daub_ensembles'],
    csv_separator=experiment_metadata['csv_separator'],
    lookback_window=experiment_metadata['lookback_window'],
    forecast_window=experiment_metadata['forecast_window'],
    timestamp_column_name=experiment_metadata['timestamp_column_name'],
    backtest_num=experiment_metadata['backtest_num'],
    feature_columns=experiment_metadata['feature_columns'],
    supporting_features_at_forecast=experiment_metadata['future_exogenous_available'],
    pipeline_types=['RandomForestRegressor', 'ExogenousRandomForestRegressor', 'SVM', 'ExogenousSVM', 'LocalizedFlattenEnsembler', 'DifferenceFlattenEnsembler', 'FlattenEnsembler', 'ExogenousLocalizedFlattenEnsembler', 'ExogenousDifferenceFlattenEnsembler', 'ExogenousFlattenEnsembler', 'MT2RForecaster', 'ExogenousMT2RForecaster', 'HoltWinterAdditive', 'HoltWinterMultiplicative', 'Bats', 'ARIMA', 'ARIMAX', 'ARIMAX_RSAR', 'ARIMAX_PALR', 'ARIMAX_RAR', 'ARIMAX_DMLR'],
    backtest_gap_length=experiment_metadata['gap_len'],
    numerical_imputation_strategy=experiment_metadata['numerical_imputation_strategy'],
)

In [33]:
pipeline_optimizer.fit(
    training_data_references=training_data_references,
    training_results_reference=training_result_reference,
)

Training job c6aff576-1a81-44df-b8ab-b29d43f12bbe completed: 100%|████████| [04:24<00:00,  2.65s/it]

{'metadata': {'created_at': '2026-04-10T18:00:46.694Z',
  'description': ' - pipeline: 72074686-e167-4f79-af87-95f9f6d62d62',
  'id': 'c6aff576-1a81-44df-b8ab-b29d43f12bbe',
  'modified_at': '2026-04-10T18:05:12.145Z',
  'name': 'custom_name - pipeline: 72074686-e167-4f79-af87-95f9f6d62d62',
  'project_id': '3b4a037e-5691-40a1-ba31-4f54c44f1f47',
  'tags': ['autoai']},
 'entity': {'description': ' - pipeline: 72074686-e167-4f79-af87-95f9f6d62d62',
  'name': 'custom_name - pipeline: 72074686-e167-4f79-af87-95f9f6d62d62',
  'pipeline': {'id': '72074686-e167-4f79-af87-95f9f6d62d62'},
  'project_id': '3b4a037e-5691-40a1-ba31-4f54c44f1f47',
  'results_reference': {'location': {'path': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts',
    'training': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe',
    'training_status': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/training-status.json',
    '_model_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/model.zip',
    'training_log': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/training.log',
    'assets_path': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/assets',
    '_training_status': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/training-status.json',
    'notebooks_path': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/notebooks'},
   'type': 'container'},
  'status': {'completed_at': '2026-04-10T18:05:12.136Z',
   'data_preprocessing': [{'input': {'columns': 5, 'rows': 1571},
     'output': {'columns': 5, 'rows': 1571},
     'props': {'type': 'truncate'},
     'stage': 'sampling'},
    {'input': {'columns': 5, 'rows': 1571},
     'output': {'columns': 5, 'rows': 1571},
     'props': {'duplicated_rows_count': 0, 'outliers_count': None},
     'stage': 'cleansing'}],
   'message': {'level': 'info',
    'text': 'Training job c6aff576-1a81-44df-b8ab-b29d43f12bbe completed'},
   'metrics': [{'context': {'intermediate_model': {'composition_steps': ['Linear'],
       'duration': 368,
       'location': {'model': '',
        'pipeline': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P21/pipeline.json',
        'pipeline_model': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P21/pipeline-model.json'},
       'name': 'P21',
       'pipeline_nodes': ['Linear', 'ARIMA'],
       'process': 'after_pipeline_execution',
       'schema_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P21/schema.json'},
      'phase': 'after_pipeline_execution',
      'prediction_type': 'forecasting',
      'timeseries': {'allocation': 0.7899427116486314,
       'allocation_rows': 1241,
       'daub_status_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P21/daub_status.json',
       'estimator': 'WatForeForecaster',
       'holdout_percentage': 0.012730744748567792,
       'holdout_rows': 20,
       'id': 'P21',
       'phase': 'after_pipeline_execution',
       'pipeline_name': 'ARIMAX_DMLR'}},
     'timestamp': '2026-04-10T18:01:57.000Z',
     'ts_metrics': {'training': {'neg_symmetric_mean_absolute_percentage_error': -23.953549222548766}}},
    {'context': {'intermediate_model': {'composition_steps': ['Linear',
        'Log',
        'DifferenceFlatten'],
       'duration': 1703,
       'location': {'model': '',
        'pipeline': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P9/pipeline.json',
        'pipeline_model': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P9/pipeline-model.json'},
       'name': 'P9',
       'pipeline_nodes': ['Linear', 'DifferenceFlatten', 'Log', 'Ensembler'],
       'process': 'after_pipeline_execution',
       'schema_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P9/schema.json'},
      'phase': 'after_pipeline_execution',
      'prediction_type': 'forecasting',
      'timeseries': {'allocation': 0.7899427116486314,
       'allocation_rows': 1241,
       'daub_status_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P9/daub_status.json',
       'estimator': 'DifferenceFlattenAutoEnsembler',
       'holdout_percentage': 0.012730744748567792,
       'holdout_rows': 20,
       'id': 'P9',
       'phase': 'after_pipeline_execution',
       'pipeline_name': 'DifferenceFlattenEnsembler'}},
     'timestamp': '2026-04-10T18:02:06.000Z',
     'ts_metrics': {'training': {'neg_symmetric_mean_absolute_percentage_error': -1.4410874147978803}}},
    {'context': {'intermediate_model': {'composition_steps': ['Linear',
        'Imputation',
        'Window',
        'RowNormalization'],
       'duration': 9374,
       'location': {'model': '',
        'pipeline': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P3/pipeline.json',
        'pipeline_model': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P3/pipeline-model.json'},
       'name': 'P3',
       'pipeline_nodes': ['Linear',
        'SmallDataWindowExogenousTransformer',
        'Imputation',
        'Window',
        'RowNormalization',
        'RandomForest'],
       'process': 'after_pipeline_execution',
       'schema_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P3/schema.json'},
      'phase': 'after_pipeline_execution',
      'prediction_type': 'forecasting',
      'timeseries': {'allocation': 0.7899427116486314,
       'allocation_rows': 1241,
       'daub_status_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P3/daub_status.json',
       'estimator': 'AutoaiTSPipeline',
       'holdout_percentage': 0.012730744748567792,
       'holdout_rows': 20,
       'id': 'P3',
       'phase': 'after_pipeline_execution',
       'pipeline_name': 'ExogenousRandomForestRegressor'}},
     'timestamp': '2026-04-10T18:02:21.000Z',
     'ts_metrics': {'training': {'neg_symmetric_mean_absolute_percentage_error': -10.297850505773493}}},
    {'context': {'intermediate_model': {'composition_steps': ['Linear'],
       'duration': 132,
       'location': {'model': '',
        'pipeline': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P15/pipeline.json',
        'pipeline_model': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P15/pipeline-model.json'},
       'name': 'P15',
       'pipeline_nodes': ['Linear', 'ARIMA'],
       'process': 'after_pipeline_execution',
       'schema_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P15/schema.json'},
      'phase': 'after_pipeline_execution',
      'prediction_type': 'forecasting',
      'timeseries': {'allocation': 0.7899427116486314,
       'allocation_rows': 1241,
       'daub_status_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P15/daub_status.json',
       'estimator': 'WatForeForecaster',
       'holdout_percentage': 0.012730744748567792,
       'holdout_rows': 20,
       'id': 'P15',
       'phase': 'after_pipeline_execution',
       'pipeline_name': 'ARIMA'}},
     'timestamp': '2026-04-10T18:02:28.000Z',
     'ts_metrics': {'training': {'neg_symmetric_mean_absolute_percentage_error': -1.4467923552221829}}},
    {'context': {'intermediate_model': {'composition_steps': ['Linear',
        'Imputation',
        'StandardScaler',
        'Window',
        'RowNormalization'],
       'duration': 1229,
       'location': {'model': '',
        'pipeline': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P4/pipeline.json',
        'pipeline_model': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P4/pipeline-model.json'},
       'name': 'P4',
       'pipeline_nodes': ['Linear',
        'SmallDataWindowExogenousTransformer',
        'Imputation',
        'StandardScaler',
        'Window',
        'RowNormalization',
        'SVM'],
       'process': 'after_pipeline_execution',
       'schema_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P4/schema.json'},
      'phase': 'after_pipeline_execution',
      'prediction_type': 'forecasting',
      'timeseries': {'allocation': 0.7899427116486314,
       'allocation_rows': 1241,
       'daub_status_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P4/daub_status.json',
       'estimator': 'AutoaiTSPipeline',
       'holdout_percentage': 0.012730744748567792,
       'holdout_rows': 20,
       'id': 'P4',
       'phase': 'after_pipeline_execution',
       'pipeline_name': 'ExogenousSVM'}},
     'timestamp': '2026-04-10T18:02:35.000Z',
     'ts_metrics': {'training': {'neg_symmetric_mean_absolute_percentage_error': -87.2715393985333}}},
    {'context': {'intermediate_model': {'composition_steps': ['Linear',
        'Log',
        'Flatten'],
       'duration': 1528,
       'location': {'model': '',
        'pipeline': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P7/pipeline.json',
        'pipeline_model': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P7/pipeline-model.json'},
       'name': 'P7',
       'pipeline_nodes': ['Linear', 'Flatten', 'Log', 'Ensembler'],
       'process': 'after_pipeline_execution',
       'schema_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P7/schema.json'},
      'phase': 'after_pipeline_execution',
      'prediction_type': 'forecasting',
      'timeseries': {'allocation': 0.7899427116486314,
       'allocation_rows': 1241,
       'daub_status_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P7/daub_status.json',
       'estimator': 'FlattenAutoEnsembler',
       'holdout_percentage': 0.012730744748567792,
       'holdout_rows': 20,
       'id': 'P7',
       'phase': 'after_pipeline_execution',
       'pipeline_name': 'FlattenEnsembler'}},
     'timestamp': '2026-04-10T18:02:43.000Z',
     'ts_metrics': {'training': {'neg_symmetric_mean_absolute_percentage_error': -1.4945584976172366}}},
    {'context': {'intermediate_model': {'composition_steps': ['Linear',
        'Window',
        'RowNormalization'],
       'duration': 4622,
       'location': {'model': '',
        'pipeline': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P1/pipeline.json',
        'pipeline_model': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P1/pipeline-model.json'},
       'name': 'P1',
       'pipeline_nodes': ['Linear',
        'Window',
        'RowNormalization',
        'RandomForest'],
       'process': 'after_pipeline_execution',
       'schema_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P1/schema.json'},
      'phase': 'after_pipeline_execution',
      'prediction_type': 'forecasting',
      'timeseries': {'allocation': 0.7899427116486314,
       'allocation_rows': 1241,
       'daub_status_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P1/daub_status.json',
       'estimator': 'AutoaiTSPipeline',
       'holdout_percentage': 0.012730744748567792,
       'holdout_rows': 20,
       'id': 'P1',
       'phase': 'after_pipeline_execution',
       'pipeline_name': 'RandomForestRegressor'}},
     'timestamp': '2026-04-10T18:02:52.000Z',
     'ts_metrics': {'training': {'neg_symmetric_mean_absolute_percentage_error': -1.5295693891724094}}},
    {'context': {'intermediate_model': {'composition_steps': ['Linear'],
       'duration': 1586,
       'location': {'model': '',
        'pipeline': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P12/pipeline.json',
        'pipeline_model': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P12/pipeline-model.json'},
       'name': 'P12',
       'pipeline_nodes': ['Linear', 'LocalizedFlattenX', 'Ensembler'],
       'process': 'after_pipeline_execution',
       'schema_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P12/schema.json'},
      'phase': 'after_pipeline_execution',
      'prediction_type': 'forecasting',
      'timeseries': {'allocation': 0.7899427116486314,
       'allocation_rows': 1241,
       'daub_status_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P12/daub_status.json',
       'estimator': 'LocalizedFlattenAutoEnsembler',
       'holdout_percentage': 0.012730744748567792,
       'holdout_rows': 20,
       'id': 'P12',
       'phase': 'after_pipeline_execution',
       'pipeline_name': 'ExogenousLocalizedFlattenEnsembler'}},
     'timestamp': '2026-04-10T18:02:58.000Z',
     'ts_metrics': {'training': {'neg_symmetric_mean_absolute_percentage_error': -1.5615963124234136}}},
    {'context': {'intermediate_model': {'composition_steps': ['Linear',
        'Trend',
        'Flatten'],
       'duration': 640,
       'location': {'model': '',
        'pipeline': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P5/pipeline.json',
        'pipeline_model': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P5/pipeline-model.json'},
       'name': 'P5',
       'pipeline_nodes': ['Linear', 'Trend', 'Flatten', 'LinearRegression'],
       'process': 'after_pipeline_execution',
       'schema_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P5/schema.json'},
      'phase': 'after_pipeline_execution',
      'prediction_type': 'forecasting',
      'timeseries': {'allocation': 0.7899427116486314,
       'allocation_rows': 1241,
       'daub_status_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P5/daub_status.json',
       'estimator': 'MT2RForecaster',
       'holdout_percentage': 0.012730744748567792,
       'holdout_rows': 20,
       'id': 'P5',
       'phase': 'after_pipeline_execution',
       'pipeline_name': 'MT2RForecaster'}},
     'timestamp': '2026-04-10T18:03:05.000Z',
     'ts_metrics': {'training': {'neg_symmetric_mean_absolute_percentage_error': -1.4486424070210644}}},
    {'context': {'intermediate_model': {'composition_steps': ['Linear',
        'Trend',
        'Flatten'],
       'duration': 669,
       'location': {'model': '',
        'pipeline': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P6/pipeline.json',
        'pipeline_model': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P6/pipeline-model.json'},
       'name': 'P6',
       'pipeline_nodes': ['Linear', 'Trend', 'Flatten', 'LinearRegression'],
       'process': 'after_pipeline_execution',
       'schema_location': 'auto_ml/8c2f2245-ef3d-477b-8d10-7994d650c48e/wml_data/39aa7057-c366-4fa2-b677-e944f9e1a71c/data/autoai-ts/c6aff576-1a81-44df-b8ab-b29d43f12bbe/data/autoai-ts/after_pipeline_execution/P6/schema.json'},
      'phase': 'after_pipeline_execution',
      'prediction_type': 'forecasting',
      'timeseries': {'allocation': 0.7899427116486314,
       'allocation_rows': 1241,

First, let's retrieve the `scoring_url` of your deployed model and your `api_key` to use in the web page's JavaScript code.

In [36]:
scoring_url = service.get_params()['entity']['status']['inference'][0]['url']

# Note: Storing API key directly in client-side code is NOT recommended for production environments.
# For demonstration purposes only.

print(f"Scoring URL: {scoring_url}")
print(f"API Key: {'*' * len(api_key)}") # Masking for display

Note: online_url and serving_urls are deprecated and will be removed in a future release. Use inference instead.
Scoring URL: https://us-south.ml.cloud.ibm.com/ml/v4/deployments/9bc1c214-09d0-472a-b984-4ef68627bc9b/predictions
API Key: ********************************************

To confirm the prediction functionality without a web page, you can create sample data and use the `service.score()` method directly in a code cell. This will print the predictions in your notebook output.

In [62]:
import pandas as pd

# Prompt the user for input for each column
fecha_input = input("Ingrese la fecha para la que desea la predicción (YYYY-MM-DD): ")
bitcoin_price_input = float(input("Ingrese el último 'Bitcoin Precio Cierre' conocido: "))
interest_rate_input = float(input("Ingrese la última 'Tasa de interes promedio' conocida: "))
etf_price_input = float(input("Ingrese el último 'ETF precio cierre' conocido: "))

# Create sample data for scoring with user-provided values
# IMPORTANT: The 'Fecha' column is NOT included in scoring_data for the model input
# because the model expects only the feature columns. The date is handled internally
# by the time-series model for forecasting the next step.
scoring_data = pd.DataFrame({
    'Bitcoin Precio Cierre': [bitcoin_price_input],
    'Tasa de interes promedio': [interest_rate_input],
    'ETF precio cierre': [etf_price_input]
})

print("\n--- Su Entrada ---")
print(f"Fecha para la predicción: {fecha_input}")
print("Datos de características ingresados:")
display(scoring_data)

Ingrese la fecha para la que desea la predicción (YYYY-MM-DD): 2026-04-11
Ingrese el último 'Bitcoin Precio Cierre' conocido: 73138
Ingrese la última 'Tasa de interes promedio' conocida: 3.64
Ingrese el último 'ETF precio cierre' conocido: 10.05

--- Su Entrada ---
Fecha para la predicción: 2026-04-11
Datos de características ingresados:

   Bitcoin Precio Cierre  Tasa de interes promedio  ETF precio cierre
0                73138.0                      3.64              10.05

In [63]:
# Make a prediction using the deployed web service
predictions = service.score(scoring_data)

print("\n--- Predicciones del Servicio Web ---")
display(predictions)
print(f"Predicción de 'Bitcoin Precio Cierre' para {fecha_input}: {predictions['predictions'][0]['values'][0][0]}")

--- Predicciones del Servicio Web ---

{'predictions': [{'fields': ['prediction'],
   'values': [[[73157.56505452981]]]}]}

Predicción de 'Bitcoin Precio Cierre' para 2026-04-11: [73157.56505452981]